spring:
  application:
    name: store
  datasource:
    url: ${MYSQL_HOST}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: ${ACCESS_TOKEN_EXPIRATION}
    refreshTokenExpiration: ${REFRESH_TOKEN_EXPIRATION}
stripe:
  secretKey: ${STRIPE_SECRET_KEY}
  webhookSecretKey: ${STRIPE_WEBHOOK_SECRET_KEY}
websiteURL: http://localhost:3000