spring:
  application:
    name: store
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: ${ACCESS_TOKEN_EXPIRATION}
    refreshTokenExpiration: ${REFRESH_TOKEN_EXPIRATION}
  profiles:
    active: dev
stripe:
  secretKey: ${STRIPE_SECRET_KEY}
  webhookSecretKey: ${STRIPE_WEBHOOK_SECRET_KEY}